# Generated by Django 5.0.2 on 2024-03-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wutyworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='no_adultos',
            new_name='principales',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='no_menores',
            new_name='secundarios',
        ),
    ]
